# Generated by Django 4.2.6 on 2023-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
