# Generated by Django 4.2.6 on 2023-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_active',
        ),
        migrations.AddField(
            model_name='event',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
